### ISSUE TITLE
Sanctioned snap?

### ISSUE THREAD

**Issue by superm1** [intel/lms#1]
Hi,

I noticed https://snapcraft.io/lms but it's listed as owned by "Alexander Usyskin".  I wanted to confirm, is that produced by Intel and they just happen to be the uploader?  Or is that a 3rd party snap?

**Comment by jsastriawan** [comment]
Alexander Usyskin is the developer for LMS and he works for Intel.

**Comment by superm1** [comment]
Great, thanks for your confirmation.
