### ISSUE TITLE
lms service not starting

### ISSUE THREAD

**Issue by anujm1** [intel/lms#17]
Since https://github.com/intel/lms/commit/52fdd2081e08e189679cc884211220802449ad21 if /etc/lms/ doesn't exist, service fails with error:
```

Nov 16 00:52:51 intel-corei7-64 systemd[149212]: lms.service: Failed to set up mount namespacing: /run/systemd/unit-root/etc/lms: No such file or directory
Nov 16 00:52:51 intel-corei7-64 systemd[149212]: lms.service: Failed at step NAMESPACE spawning /usr/bin/lms: No such file or directory
Nov 16 00:52:51 intel-corei7-64 systemd[1]: lms.service: Main process exited, code=exited, status=226/NAMESPACE
```

Creating /etc/lms fixes it. Should that directory be installed now?

**Comment by ausyskin** [comment]
UNS/linux_scripts/postinst has this. How do you install LMS?

**Comment by anujm1** [comment]
I use Yocto. I will add it to the recipe. Thank you.
