### ISSUE TITLE
IPv6 disabled

### ISSUE THREAD

**Issue by StumpfMichael** [intel/lms#7]
LMS together with ACE has been build on CentOS 7.8.

When the OS is started with ipv6.disable=1 a connection to port 16992 is no longer possible.

**Comment by StumpfMichael** [comment]
It was verified again with netstat -lnt:
ipv6 enabled: port 16992 and 623, ip address 0.0.0.0, open for listening
ipv6 disabled: closed

**Comment by ausyskin** [comment]
Can you, please, enable logging (https://github.com/intel/lms/blob/master/UNS/linux_scripts/lms_enable_logging_severity.sh), restart LMS and attach the LMS logs. (journalctl -u lms)

**Comment by StumpfMichael** [comment]
Hi, thank you for your attention and fast response.
LMS never run as a service on our CentOS machines, it always failed. We just started it by script (./lms &), modified the amt configuration and killed the process after.
Attached is the logfile when we try to start it as a service.

[log.txt](https://github.com/intel/lms/files/6422254/log.txt)

**Comment by ausyskin** [comment]
There are not much there. In general LMS writes to syslog, maybe there will be more information.
And to look at ipv6 issue let's look at syslog for a script (./lms &) run.

**Comment by StumpfMichael** [comment]
This is the information from /var/log/messages, perhaps more interesting is the output, if you start "strace -f ./lms"


[log.txt](https://github.com/intel/lms/files/6422593/log.txt)
[strace.txt](https://github.com/intel/lms/files/6422630/strace.txt)

**Comment by StumpfMichael** [comment]
Hi, I would like to suggest to solve the problems one by one. I open a new issue regarding the failure to run lms as a service on CentOS. There I will give you some information about the environment and the output of journalctl -u lms.

When we have solved that we come back here and look what happens when IPv6 is disabled. What do you think?

**Comment by ausyskin** [comment]
We have reproduced issue with IPv6 in our lab. I'll look what can be done about it.

**Comment by StumpfMichael** [comment]
So what do you think, will it be feasible?

**Comment by StumpfMichael** [comment]
May I ask if you already have a release date in mind for this workaround?

**Comment by ausyskin** [comment]
This week, I hope.

**Comment by ausyskin** [comment]
Fixed in v2120.0.0.0

**Comment by StumpfMichael** [comment]
Thank's a lot, great product, it's a pleasure to use it.
