### ISSUE TITLE
lms as a service on CentOS

### ISSUE THREAD

**Issue by StumpfMichael** [intel/lms#8]
The last version of lms has been compiled with devtoolset-9 on a plane CentOS 7.9 Gnome together with ACE 7.0.

In the numerous attempts I could recognize the following:
Apparently there are problems to communicate with the  device /dev/mei0. There have been messages like "no privilage to access", "not appropriate IOCTL" or "device is busy". The lms tries to access the devices /dev/mei1 to 3 which are not in the system. After some time it gives up and fails.

Attached you can find more information about the version of Intel ME and the output of journalctl -u lms.

[mei.txt](https://github.com/intel/lms/files/6426876/mei.txt)
[journal_-u_lms.txt](https://github.com/intel/lms/files/6426878/journal_-u_lms.txt)

**Comment by ausyskin** [comment]
Can you please run 'cat /sys/kernel/debug/mei0/meclients' and attach results here?

**Comment by ausyskin** [comment]
Do you running any other tools that communicate with MEI?
In any case, please attach 'cat /sys/kernel/debug/mei0/active' and dmesg

**Comment by StumpfMichael** [comment]
I am not aware of any other tool communicating with MEI.

As I told you before, running standalone as ( lms & ) works. I can then connect with the browser to localhost:16992.

[clients.txt](https://github.com/intel/lms/files/6427990/clients.txt)

[dmesg.txt](https://github.com/intel/lms/files/6428006/dmesg.txt)

**Comment by StumpfMichael** [comment]
I forgot to send:
[active.txt](https://github.com/intel/lms/files/6428126/active.txt)

**Comment by ausyskin** [comment]
You have a fairly old hardware, so some of failures are expected.
But not the failures are the reason for systemd to stop service.
The service unit is declare as DBus service and systemd can't see DBus registration thus stopping service as not responding after timeout.
Have you copied DBus files as explained in https://github.com/intel/lms/blob/master/UNS/DBusService/README?
Are the paths in README are valid for CentOS?

**Comment by StumpfMichael** [comment]
Ok, I had to copy com.intel.amt.lms.conf to /etc/dbus-1/system.d/. It was automatically copied to /usr/local/etc/dbus-1/system.d by make install and I was not aware of having to do something manually.
The other file was already correctly installed. The service immediately started successfully, so the paths should be valid for CentOS.

Thank you a lot for your help!

I hope it is the right way that I close the issue after your solution.

**Comment by ausyskin** [comment]
May be -DCMAKE_INSTALL_PREFIX=/usr will help in this case.
Will add some notes in README about that possibility

**Comment by StumpfMichael** [comment]
Just to give you the complete picture of my installation, I found logrotate.d/lms and rsyslog.d//20-lms.conf as well in /usr/local/etc and copied them to /etc/.

**Comment by ausyskin** [comment]
So CentOS needs -DCMAKE_INSTALL_PREFIX=/usr too. Will add that info to README,md
